name: Unit Tests
on: [push]
jobs:

  unittest-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Prepare The Environment
        run: cp .env.example .env
      - name: Create Database
        run: php artisan migrate:fresh --seed --env=dusk.local
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Run Unit Tests
        env:
          APP_URL: "http://127.0.0.1:8000"
        run: php artisan test --env=dusk.local
